### ISSUE TITLE
Can you please supply a .jed file for programming the CPLD?

### ISSUE THREAD

**Issue by ZaPpi3** [PR77/A500_ACCEL_RAM_IDE-Rev-2#3]
I cannot seem to open the project in my ISE version as it is complaining that my version is older than the one used for the project.

Could you please make it simple to program by creating a .jed file for use in impact?

Thank you in advance.

**Comment by PR77** [comment]
Hello,

JED file added;

https://github.com/PR77/A500_ACCEL_RAM_IDE-Rev-2/blob/master/Logic/jed/ACCEL_RAM_IDE.jed
