### ISSUE TITLE
AT25 version ?

### ISSUE THREAD

**Issue by nobodyisinocent** [PR77/A500_ACCEL_RAM_IDE-Rev-2#4]
Hello,

Thanks a lot for your very cool project.
I'd like to know the exact reference of AT25 you used onto the board.
There are different memory capacities available.

Thank you very much!

Best regards,
Franck

**Comment by PR77** [comment]
Hi There,

Just FYI - please see point Known Issues (in the main README.md) #2, "Correct SPI Flash footprint. Or considering to remove it as I see no immediate benefit.". You can use any SPI Flash here however I have not finished the amiga side SW to use it. This would need to be done.

When I get around to updating this PCB (there are several improvements I want to do) I will actually remove the SPI Flash.

**Comment by nobodyisinocent** [comment]
Hi,

Thanks a lot for your answer !
I'll check the Know Issues link.

Thank you also for sharing your work !
Franck
