### ISSUE TITLE
How to boot from HDD/CF 

### ISSUE THREAD

**Issue by retroman75** [PR77/A500_ACCEL_RAM_IDE-Rev-2#5]
Hi there , 
I'm new in Amiga word , I have build one for my safe and struggling how to boot A500 from it ? Is is possible without FDD boot disk ? If kernel mod is needed by uploading IDE.devide lib. is necessary then how to do it ?  . Anybody can help ? 
Thank you !

**Comment by PR77** [comment]
Hi there, currently kernel mod is needed if you don't want to use a bootdisk. Have a look here for details;

#2

**Comment by retroman75** [comment]
Could you please give little more info about that kernel mod ? My understanding is that I will have to add ide.device lib. to my existing ROM image ?... if so , how to do it ? any software is needed ? . Please help :) 
Thank you

**Comment by Twisty59** [comment]
Hello,

You need to have a least the ide.device working on $EF0000 to boot. You can just using a floppy disk for booting.
If you want to make it autoboot you need to make a custom rom with ide.device AND bootide.device, you will need to remove scsi.device from the original rom. 
I have made a custom rom 3.1 and autoboot work very well on this board ! :)

**Comment by retroman75** [comment]
Thanks for fast replay , but is there any software to manipulate Kernal image  ?
PS.
Where can I get a copy of bootide.device file ?

**Comment by Twisty59** [comment]
> well , nobody like to help so I will have to do it for my safe .

This is not really nice to read this since I'm trying to help you. 

> Thanks for fast replay , but is there any software to manipulate Kernal image ? PS. Where can I get a copy of bootide.device file ?

You need to extract your ROM content with Remus, remove scsi.device and add both ide.device and bootide.device then create the custom rom.

Here is the source for bootide.device : https://gitlab.com/MHeinrichs/AddBootNode
Its already include in last version on ide.device : https://gitlab.com/MHeinrichs/AIDE/-/blob/master/device/new-version/IDE-DEVICE2.59.zip

**Comment by retroman75** [comment]
Thank you Twisty59 , you are the best !

**Comment by Mingo12** [comment]
@Twisty59 
Can you please give me more information about creating the kickstart? I removed scsi.device and added ide.device and bootide.device with Remus. With the patched Kickstart 3.1, CF won't boot and floppy disks won't boot either.

**Comment by Twisty59** [comment]
Did you have the right ide.device working on $EF0000 ? I maybe still have my custom 3.1 that work perfect with this board. If you have Discord, I can give it to you.

**Comment by Mingo12** [comment]
In the meantime I got a patched ROM from someone. Thank you anyway!
