### ISSUE TITLE
Cdtv, no ide and no ram at boot

### ISSUE THREAD

**Issue by HalifaxAmiga** [PR77/A500_ACCEL_RAM_IDE-Rev-2#6]
Hello, would it be possible to offer a firmware with only the processor enabled? (Fastram and IDE disabled)
It’s for trying to use it on a CDTV.
Thank you

Halifax.

**Comment by PR77** [comment]
Sure, I can try to prepare this over the next few days. You do know that without FastRAM the CPU performance increase will be very limited. Why do you want these peripheries disabled?

**Comment by PR77** [comment]
Hey Halifax,

Thanks for your patience. You'll find the Accelerator Only JED here;

[https://github.com/PR77/A500_ACCEL_RAM_IDE-Rev-2/blob/master/Logic/jed/ACCEL.jed](url)

Let me know how it works for you - I'm interested to know the results. Perhaps some screen shots. :) #
